# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
- package-ecosystem: nuget
  directories: 
    - "*"
  schedule:
    interval: daily
  target-branch: "main"    
  labels:
    - 'dependencies'
  reviewers:
    - 'microsoft/botframework-sdk'    

  
#- package-ecosystem: dotnet-sdk
#  directory: "/"
#  schedule:
#    interval: daily
#  target-branch: "main"    
#  labels:
#    - 'dependencies'
#  reviewers:
#    - 'microsoft/botframework-sdk'      
