# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
- package-ecosystem: nuget
  directory: /
  schedule:
    interval: daily
  labels:
    - 'dependencies'
  reviewers:
    - 'microsoft/botframework-sdk'    
  groups:
    nerdbank-gitversioning:
      patterns:
      - nbgv
      - nerdbank.gitversioning
    xunit:
      patterns:
      - 'xunit*'
- package-ecosystem: dotnet-sdk
  directory: /
  schedule:
    interval: daily
  labels:
    - 'dependencies'
  reviewers:
    - 'microsoft/botframework-sdk'      
