<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ComponentAreaName>CplTests.Samples.A2A</ComponentAreaName>
    <SignAssembly>true</SignAssembly>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <IsTestProject Condition="'$(TargetFramework)' != '' and '$(TargetFramework)' != 'net10.0'">false</IsTestProject>
  </PropertyGroup>

  <Import Project="..\\..\\Build.Common.core.props" />

  <ItemGroup>
    <Compile Remove="Properties\\**" />
    <EmbeddedResource Remove="Properties\\**" />
    <None Remove="Properties\\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\libraries\Extensions\Microsoft.Agents.Extensions.A2A\Microsoft.Agents.Extensions.A2A.csproj" />
    <ProjectReference Include="..\..\samples\A2A\A2AAgent\A2AAgent.csproj" Aliases="A2AAgentSample" />
    <ProjectReference Include="..\..\samples\A2A\A2AClient\A2AClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
