// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.Agents.Authentication.EntraAuthSidecar.Model
{
    /// <summary>
    /// RFC 7807 ProblemDetails parsed from sidecar error responses.
    /// </summary>
    internal class SidecarProblemDetails
    {
        /// <summary>A URI reference that identifies the problem type.</summary>
        public string Type { get; set; }

        /// <summary>A short, human-readable summary of the problem type.</summary>
        public string Title { get; set; }

        /// <summary>The HTTP status code generated by the origin server.</summary>
        public int? Status { get; set; }

        /// <summary>A human-readable explanation specific to this occurrence of the problem.</summary>
        public string Detail { get; set; }

        /// <summary>A URI reference that identifies the specific occurrence of the problem.</summary>
        public string Instance { get; set; }
    }
}
