// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text.Json.Serialization;

namespace Microsoft.Agents.Hosting.A2A.Models
{
    /// <summary>
    /// Represents a tangible output generated by the agent during a task. Artifacts are the 
    /// results or products of the agent's work.
    /// </summary>
    public record Artifact
    {
        public static readonly Artifact Empty = new() { ArtifactId = Guid.NewGuid().ToString("N") };

        /// <summary>
        /// Identifier for the artifact generated by the agent.
        /// </summary>
        [JsonPropertyName("artifactId")]
        public required string ArtifactId { get; init; }

        /// <summary>
        /// Descriptive name for the artifact.
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get; init; }

        /// <summary>
        /// Human-readable description of the artifact.
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get; init; }

        /// <summary>
        /// Content of the artifact, as one or more Part objects. Must have at least one.
        /// </summary>
        [JsonPropertyName("parts")]
        public ImmutableArray<Part> Parts { get; init; } = [];

        /// <summary>
        /// Arbitrary key-value metadata associated with the artifact.
        /// </summary>
        [JsonPropertyName("metadata")]
        public IReadOnlyDictionary<string, object>? Metadata { get; set; }

        /// <summary>
        /// A list of extension URIs that contributed to this artifact.
        /// </summary>
        [JsonPropertyName("extensions")]
        public ImmutableArray<string>? Extensions { get; init; }
    }
}