// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text.Json.Serialization;

namespace Microsoft.Agents.Hosting.A2A.Models
{
    /// <summary>
    /// Represents a single communication turn or a piece of contextual information between a 
    /// client and an agent. Messages are used for instructions, prompts, replies, and status updates.
    /// </summary>
    public record Message
    {
        public enum RoleType
        {
            User,
            Agent
        };

        [JsonPropertyName("kind")]
        public string Kind { get; } = "message";

        /// <summary>
        /// Indicates the sender: "user" (from A2A Client) or "agent" (from A2A Server).
        /// </summary>
        [JsonPropertyName("role")]
        public required RoleType Role { get; init; }

        /// <summary>
        /// Array of content parts. Must contain at least one part.
        /// </summary>
        [JsonPropertyName("parts")]
        public required ImmutableArray<Part> Parts { get; init; }

        /// <summary>
        /// Message identifier generated by the message sender
        /// </summary>
        [JsonPropertyName("messageId")]
        public required string MessageId { get; init; }

        /// <summary>
        /// Task identifier the current message is related to
        /// </summary>
        [JsonPropertyName("taskId")]
        public string? TaskId { get; init; }

        /// <summary>
        /// Context identifier the message is associated with
        /// </summary>
        [JsonPropertyName("contextId")]
        public string? ContextId { get; init; }

        /// <summary>
        /// Arbitrary key-value metadata associated with this message.
        /// </summary>
        [JsonPropertyName("metadata")]
        public IReadOnlyDictionary<string, object>? Metadata { get; set; }

        /// <summary>
        /// List of tasks referenced as contextual hint by this message.
        /// </summary>
        [JsonPropertyName("referenceTaskIds")]
        public ImmutableArray<string>? ReferenceTaskIds { get; init; }
    }
}