<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IncludeAspNetSampleHelpers>false</IncludeAspNetSampleHelpers>
    <RootNamespace>Microsoft.Agents.Samples.A2ACli</RootNamespace>
    <AssemblyName>A2ACli</AssemblyName>
    <UserSecretsId>AgentsSdk-A2ACli</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="A2A" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Microsoft.Agents.Samples.A2A.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
