// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System.Text.Json.Serialization;

namespace Microsoft.Agents.Hosting.A2A.Protocol
{
    /// <summary>
    /// HTTP Authentication security scheme.
    /// </summary>
    public record HTTPAuthSecurityScheme : SecurityScheme
    {
        /// <summary>
        /// A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually
        /// generated by an authorization server, so this information is primarily for documentation
        /// purposes.
        /// </summary>
        [JsonPropertyName("bearerFormat")]
        public string? BearerFormat { get; init; }

        /// <summary>
        /// The name of the HTTP Authentication scheme to be used in the Authorization header as defined
        /// in RFC7235. The values used SHOULD be registered in the IANA Authentication Scheme registry.
        /// The value is case-insensitive, as defined in RFC7235.
        /// </summary>
        [JsonPropertyName("scheme")]
        public required string Scheme { get; init; }
    }
}
